import{a as m,i as E,S as g}from"./assets/vendor-b0d10f48.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const s of e)if(s.type==="childList")for(const c of s.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&n(c)}).observe(document,{childList:!0,subtree:!0});function o(e){const s={};return e.integrity&&(s.integrity=e.integrity),e.referrerPolicy&&(s.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?s.credentials="include":e.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function n(e){if(e.ep)return;e.ep=!0;const s=o(e);fetch(e.href,s)}})();const S="45098988-0aca0e44808ea00320f5f0e3c";m.defaults.baseURL="https://pixabay.com/api/";async function b(r,t=1,o=15){try{return(await m.get("",{params:{key:S,q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,page:t,perPage:o}})).data.hits}catch{throw new Error("Failed to fetch images")}}function w(r){return r.map(({webformatURL:t,largeImageURL:o,tags:n,likes:e,views:s,comments:c,downloads:v})=>` 
      <a href="${o}" class="gallery-link">
        <img src="${t}" alt="${n}" class="gallery-image" />
         <div class="info-gallery">
          <p class="info-gallery-item"><b>Likes</b>${e}</p>
          <p class="info-gallery-item"><b>Views</b>${s}</p>
          <p class="info-gallery-item"><b>Comments</b>${c}</p>
          <p class="info-gallery-item"><b>Downloads</b>${v}</p>
        </div>
        </a>
    `).join("")}function i(r){E.error({title:"Error",position:"topRight",message:r})}const p=document.querySelector(".form-search"),h=document.querySelector(".gallery"),y=document.querySelector(".loader"),L=document.querySelector('[data-action="load-more"]');let a,d=1,f=0,u="";class q{constructor(t,o){this.buttonEl=t,this.hiddenClass=o}hide(){this.buttonEl.classList.add(this.hiddenClass)}show(){this.buttonEl.classList.remove(this.hiddenClass)}disable(){this.buttonEl.disabled=!0}enable(){this.buttonEl.disabled=!1}}const l=new q(L,"is-hidden");p.addEventListener("submit",async r=>{if(r.preventDefault(),u=r.target.elements.query.value.trim(),d=1,!u){i("Search field cannot be empty");return}y.style.display="flex",l.hide();try{const t=await b(u,d);t.length===0?(i("Sorry, there are no images matching your search query. Please try again!"),h.innerHTML="",l.hide()):(h.innerHTML=w(t),a==null||a.destroy(),a=new g(".gallery-link",{captionsData:"alt",captionDelay:250}),f=t.length,l.show(),f<15&&(l.hide(),i("We're sorry, but you've reached the end of search results.")))}catch{i("Failed to fetch images")}finally{y.style.display="none",p.reset()}});L.addEventListener("click",async()=>{d+=1,y.style.display="flex";try{const r=await b(u,d);if(r.length===0)l.hide(),i("На жаль, ви досягли кінця результатів пошуку.");else{h.insertAdjacentHTML("beforeend",w(r)),a==null||a.destroy(),a=new g(".gallery-link",{captionsData:"alt",captionDelay:250});const{height:t}=document.querySelector(".gallery-image").getBoundingClientRect();window.scrollBy({top:t*2,behavior:"smooth"}),f+=r.length,f>=15*d&&(l.hide(),i("На жаль, ви досягли кінця результатів пошуку."))}}catch{i("Не вдалося завантажити зображення")}finally{y.style.display="none"}});
//# sourceMappingURL=commonHelpers.js.map
