import{a as m,i as g,S as b}from"./assets/vendor-b0d10f48.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const i of t.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&a(i)}).observe(document,{childList:!0,subtree:!0});function s(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function a(e){if(e.ep)return;e.ep=!0;const t=s(e);fetch(e.href,t)}})();const L="45098988-0aca0e44808ea00320f5f0e3c";m.defaults.baseURL="https://pixabay.com/api/";async function w(o,r=1,s=15){try{return(await m.get("",{params:{key:L,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,page:r,perPage:s}})).data.hits}catch{throw new Error("Failed to fetch images")}}function E(o){return o.map(({webformatURL:r,largeImageURL:s,tags:a,likes:e,views:t,comments:i,downloads:h})=>` 
      <a href="${s}" class="gallery-link">
        <img src="${r}" alt="${a}" class="gallery-image" />
         <div class="info-gallery">
          <p class="info-gallery-item"><b>Likes</b>${e}</p>
          <p class="info-gallery-item"><b>Views</b>${t}</p>
          <p class="info-gallery-item"><b>Comments</b>${i}</p>
          <p class="info-gallery-item"><b>Downloads</b>${h}</p>
        </div>
        </a>
    `).join("")}function l(o){g.error({title:"Error",position:"topRight",message:o})}const d=document.querySelector(".form-search"),u=document.querySelector(".gallery"),f=document.querySelector(".loader"),p=document.querySelector('[data-action="load-more"]');let n,y=1,S=0;class q{constructor(r,s){this.buttonEl=r,this.hiddenClass=s}hide(){this.buttonEl.classList.add(this.hiddenClass)}show(){this.buttonEl.classList.remove(this.hiddenClass)}disable(){this.buttonEl.disabled=!0}enable(){this.buttonEl.disabled=!1}}const c=new q(p,"is-hidden");d.addEventListener("submit",async o=>{o.preventDefault();const r=o.target.elements.query.value.trim();if(y=1,!r){l("Search field cannot be empty");return}f.style.display="flex",c.hide();try{const s=await w(r,y);s.length===0?(l("Sorry, there are no images matching your search query. Please try again!"),u.innerHTML=""):(u.innerHTML=E(s),n==null||n.destroy(),n=new b(".gallery-link",{captionsData:"alt",captionDelay:250}),S=s.length,c.show())}catch{l("Failed to fetch images")}finally{f.style.display="none",d.reset()}});console.log(c);console.dir(p);
//# sourceMappingURL=commonHelpers.js.map
